version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: veera_postgres4
    environment:
      POSTGRES_DB: hr_task_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5203:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - veera_net

  backend:
    build:
      context: ./Backend
    container_name: veera_backend4
    ports:
      - "3103:3103"
    depends_on:
      - postgres
    networks:
      - veera_net

  frontend:
    build:
      context: ./Frontend
    container_name: veera_frontend4
    ports:
      - "8206:80"
    networks:
      - veera_net

  hr:
    build:
      context: ./HR
    container_name: veera_hr4
    ports:
      - "8207:80"
    networks:
      - veera_net

volumes:
  pgdata:

networks:
  veera_net:

